language: cpp

os:
    - osx
    - linux

before_install: |- 
                if  [ "$TRAVIS_OS_NAME" == "osx" ]
                then
                    brew update
                    brew install ninja
                    if [ ! -d /usr/local/opt/qt5 ]
                    then
                        brew install qt5
                    fi
                fi
                if [ "$TRAVIS_OS_NAME" == "linux" ]
                then
                    sudo add-apt-repository -y ppa:beineri/opt-qt532
                    sudo add-apt-repository -y ppa:kubuntu-ppa/backports
                    sudo apt-get -qq update
                    sudo apt-get install -q qt53base qt53tools qt53quick1 qt53quickcontrols qt53websockets qt53multimedia
                    sudo apt-get install -q ninja-build cmake
                    source /opt/qt53/bin/qt53-env.sh
                fi
                if [ ! -d ~/snore_work ]
                then
                    mkdir -p ~/snore_work
                    mkdir -p ~/snore_work/git
                    cd ~/snore_work/git
                    git clone -q git://anongit.kde.org/extra-cmake-modules.git
                    git clone -q https://github.com/Snorenotify/SnoreGrowl.git
                    mkdir -p ~/snore_work/build
                    cd ~/snore_work/build
                    mkdir -p ~/snore_work/build/extra-cmake-modules
                    cd ~/snore_work/build/extra-cmake-modules
                    cmake -G"Ninja" ~/snore_work/git/extra-cmake-modules -DCMAKE_INSTALL_PREFIX=~/snore_work/installs/
                    ninja install
                    mkdir -p ~/snore_work/build/snoregrowl && cd ~/snore_work/build/snoregrowl
                    cmake -G"Ninja" ~/snore_work/git/SnoreGrowl -DCMAKE_INSTALL_PREFIX=~/snore_work/installs/
                    ninja install
                fi
  
compiler:
  - clang
  - gcc
  
script: |-
        cd $TRAVIS_BUILD_DIR
        mkdir build
        cd build
        if [ "$TRAVIS_OS_NAME" == "osx" ]
        then
            cmake -G"Ninja" .. -DCMAKE_INSTALL_PREFIX=~/snore_work/installs/ -DCMAKE_PREFIX_PATH=/usr/local/opt/qt5
        fi
        if [ "$TRAVIS_OS_NAME" == "linux" ]
        then
            cmake -G"Ninja" .. -DCMAKE_INSTALL_PREFIX=~/snore_work/installs/
        fi
        ninja install

cache:
    directories:
        - $HOME/snore_work
        - /usr/local/opt/qt5

    
notifications:
    irc: "chat.freenode.net#snorenotify"

# addons:
  # apt:
    # sources:
    # - kubuntu-backports 
    # packages:
    # - cmake
    # - qtbase5-dev
    # - qtquick1-5-dev
    # - qttools5-dev
    # - extra-cmake-modules
    