version: '{build}'
branches:
  only:
  - master
build_script:
- ps: if ( !(Test-Path "$env:APPVEYOR_BUILD_FOLDER\ci\appveyorHelp.psm1")) {Start-FileDownload https://raw.githubusercontent.com/TheOneRing/appVeyorHelp/master/appveyorHelp.psm1 -FileName $env:APPVEYOR_BUILD_FOLDER\ci\appveyorHelp.psm1 }
- ps: .\ci\appveyor.ps1

test: off

cache:
- work\git -> ci\appveyor.ps1
- work\install -> ci\appveyor.ps1
- C:\ProgramData\chocolatey\bin -> ci\appveyor.ps1
- C:\ProgramData\chocolatey\lib -> ci\appveyor.ps1
- C:\tools -> ci\appveyor.ps1
- ci\appveyorHelp.psm1 -> ci\appveyor.ps1

environment:
    matrix:
    #mingw
    - COMPILER: MINGW
    #msvc
    - COMPILER: MSVC
    
artifacts:
    - path: work\image
      name: $(APPVEYOR_PROJECT_NAME)
      