version: '{build}'
branches:
  only:
  - master
build_script:
- ps: .\ci\appveyor.ps1

test: off

cache:
- work\git -> appveyor.yml
- work\install -> appveyor.yml

environment:
    matrix:
    #mingw
    - COMPILER: MINGW
    #msvc
    - COMPILER: MSVC
    
artifacts:
    - path: work\image
      name: $(APPVEYOR_PROJECT_NAME)
      
#upodate cache 1