version: '{build}'
branches:
  only:
  - master
build_script:
- ps: >-
   & "$env:APPVEYOR_BUILD_FOLDER\ci\msvc.ps1"

cache:
- work\git -> appveyor.yml

environment:
    matrix:
    #mingw
    - COMPILER: MINGW
    #msvc
    - COMPILER: MSVC