version: '{build}'
branches:
  only:
  - master
build_script:
- ps: .\ci\appveyor.ps1

test: off

cache:
- work\git -> ci\appveyor.ps1
- work\install -> ci\appveyor.ps1
- C:\ProgramData\chocolatey\bin -> ci\appveyor.ps1
- C:\ProgramData\chocolatey\lib -> ci\appveyor.ps1

environment:
    matrix:
    #mingw
    - COMPILER: MINGW
    #msvc
    - COMPILER: MSVC
    
artifacts:
    - path: work\image
      name: $(APPVEYOR_PROJECT_NAME)
      